version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # Referencing the Dockerfile in frontend folder
    container_name: react-frontend
    ports:
      - '5173:80' # Nginx exposes the app on port 5173
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    networks:
      - backend

networks:
  backend:
    external: true
    name: task-management-network
