"""update delete cascade for notes and document embedding table

Revision ID: bd7ac7384ee0
Revises: 8ddefbb508d1
Create Date: 2025-05-08 08:50:57.977418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7ac7384ee0'
down_revision: Union[str, None] = '8ddefbb508d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'document_embeddings', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    # ### end Alembic commands ###
